### ISSUE TITLE
Recent Image is not working for me NAND or SD

### ISSUE THREAD

**Issue by shleeable** [RightToPrivacy/Pine64-Mesh-Related#3]
I cannot get PineDio-RAK-Armbian_11-30-2022.img.xz to boot.

The preview release boots on NAND and SD.

**Comment by wmehanna** [comment]
Using Pine 64 LTS board, I can confirm that: 
- The image PineDio-RAK-Armbian_11-30-2022.img.xz doesn't boot at all on EMMC or micro sd, no hdmi or ssh access available.
- The image OnPineDio-RAK-Armbian_09-25-2022.img.xz does boot, has hdmi working and can be accessed by ssh on both EMMC and micro sd card.

**Comment by wmehanna** [comment]
@shleeable After debugging on the serial port with an UART usb dongle, I was able to see that the image provided doesn't have the right u-boot binary file.  It happens that I have an a64 lts v2 board with different micro-controller to initialize the offset for the dram, so it won't find it then doesn't boot.
[u-boot-sunxi-with-spl.zip](https://github.com/RightToPrivacy/Pine64-Mesh-Related/files/10421380/u-boot-sunxi-with-spl.zip)

you need to flash u-boot-sunxi-with-spl.bin [u-boot-sunxi-with-spl.zip](https://github.com/RightToPrivacy/Pine64-Mesh-Related/files/10421380/u-boot-sunxi-with-spl.zip) using  dd if=/path/to/u-boot-sunxi-with-spl.bin of=dev=disk10 bs=8k seek=1

I hope that explanation makes sense for you.

Thanks to @gamiee on discord for his help on this one.

**Comment by RightToPrivacy** [comment]
Thank you for filing!
